# Learning Vector in Numpy

In [22]:
import numpy as np 
import matplotlib.pyplot as plt

# NOTE: these lines define global figure properties used for publication.
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg') # display figures in vector format
plt.rcParams.update({'font.size':14}) # set global font size

In [23]:
asList  = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec  = np.array([ [1,2,3] ]) # 2D array - row
colVec  = np.array([ [1],[2],[3] ]) # 2D array - column

In [24]:
print(f'asList:  {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec:  {rowVec.shape}')
print(f'colVec:  {colVec.shape}')

asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


In [25]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])
vPlusW = v+w
print(vPlusW)
# uPlusW = u+w # error! dimensions mismatched!

[14 25 36]


Broadcasting

In [26]:
v = np.array([[4,5,6]]) # row vector
w = np.array([[10,20,30]]).T # column vector
v+w

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [27]:
s = 2
a = [3,4,5] # as list
b = np.array(a) # as np array
print(a*s)
print(b*s) #scalar-vector multiplication

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


In [28]:
s = 2
v = np.array([3,6])
s+v 

array([5, 8])

In [29]:
v = np.array([[1,2,3]]).T # col vector
print(v)
w = np.array([[10,20]])   # row vector
v + w # addition with broadcasting

[[1]
 [2]
 [3]]


array([[11, 21],
       [12, 22],
       [13, 23]])

# Norm 
The magnitude of a vector—​also called the geometric length or the norm—is the distance from tail to head of a vector, and is computed using the standard Euclidean distance formula: the square root of the sum of squared vector elements

In [30]:
v = np.array([1,2,3,7,8,9])
v_dim = len(v)  # math dimensionality - magnitude
print(v_dim)
v_mag = np.linalg.norm(v) # math magnitude, length, or norm
print(v_mag)

6
14.422205101855956


In [33]:
# the function
def normOfVect(v):
  return np.sqrt(np.sum(v**2))

# test it on a unit-norm vector
w = np.array([0,0,1])
print( normOfVect(w) )

# non-unit-norm vector, and confirm using np.linalg.norm
w = np.array([1,2,3])
print( normOfVect(w),np.linalg.norm(w) )

1.0
3.7416573867739413 3.7416573867739413


In [34]:
# define function for creating unit vector of a vector input
def createUnitVector(v):
  # get vector norm
  mu = np.linalg.norm(v)
  # return unit vector
  return v / mu

# test on a unit vector
w = np.array([0,1,0])
print( createUnitVector(w) )

# test on a non-unit vector that is easy to confirm
w = np.array([0,3,0])
print( createUnitVector(w) )

# test on a non-unit vector
w = np.array([13,-5,7])
uw = createUnitVector(w)
print( uw ), print(' ')
# confirm the vectors' norms
print( np.linalg.norm(w),np.linalg.norm(uw) )

# what happens with the zeros vector?
print('\n\n\n') # just some spaces
createUnitVector( np.zeros((4,1)) )

[0. 1. 0.]
[0. 1. 0.]
[ 0.83395039 -0.32075015  0.44905021]
 
15.588457268119896 0.9999999999999999






/var/folders/pb/27nkdx3177739j51_cy47qzh0000gn/T/ipykernel_8497/4220783721.py:6: RuntimeWarning: invalid value encountered in divide
  return v / mu


array([[nan],
       [nan],
       [nan],
       [nan]])

# Dot Product

- The dot product can be interpreted as a measure of similarity or mapping between two vectors. 
- Defined as the product (norm) of the magnitudes of the two vectors, scaled by the cosine of the angle between them

In [31]:
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

np.int64(70)

In [32]:
a = np.array([ 0,1,2 ])
b = np.array([ 3,5,8 ])
c = np.array([ 13,21,34 ])

# the dot product is distributive
res1 = np.dot( a, b+c )
res2 = np.dot( a,b ) + np.dot( a,c )

print(res1, res2)

110 110


In [35]:
# the row vector to transpose
v = np.array([[1,2,3]])

# initialize the column vector
vt = np.zeros((3,1))

# direct implementation of the formula using a for loop
for i in range(v.shape[1]):
  vt[i,0] = v[0,i]

# confirm!
print(v), print(' ')
print(vt)

# Note about data types: The two vectors actually have different data types
#  (ints vs. floats). That happened because I defined v using ints while the default type
#  for np.zeros is float. You can match data types in several ways, including: 
#  (1) write 3. instead of 3 when creating v; (2) use dtype=np.float as an optional input.

[[1 2 3]]
 
[[1.]
 [2.]
 [3.]]


In [36]:
# some vector
c = np.random.randn(5)

# squared norm as dot product with itself
sqrNrm1 = np.dot(c,c)

# squared norm via our function from exercise 1
sqrNrm2 = normOfVect(c)**2

# print both to confirm they're the same
print( sqrNrm1 )
print( sqrNrm2 )

4.049180948573183
4.0491809485731824


# Orthogonal Vector Decomposition

- \beta is a scaled version of a. To project a point at the head of b onto a vector a with minimum distance, we need a formula to compute such that the length of the projection vector (b - \beta*a) is minimized

- a^T * (b-\beta*a) = 0

- Our goal is to decompose the target vector into two other vectors such that (1) those two vectors sum to the target vector, and (2) one vector is orthogonal to the reference vector while the other is parallel to the reference vector. 

In [37]:
# generate random R2 vectors (note: no orientation here! we don't need it for this exercise)
t = np.random.randn(2)
r = np.random.randn(2)

print(t, r)

# the decomposition
t_para = r * (np.dot(t,r) / np.dot(r,r))
t_perp = t - t_para

# confirm that the two components sum to the target
print(t)
print( t_para+t_perp )

# confirm orthogonality (dot product must be zero!)
print(np.dot(t_para,t_perp) )

# Note about this result: Due to numerical precision errors, 
#   you might get a result of something like 10^-17, which can be interpretd as zero.

[-0.94709373  1.34905682] [ 0.09192604 -0.05909545]
[-0.94709373  1.34905682]
[-0.94709373  1.34905682]
-5.551115123125783e-17
